Firehose/Firehose.Web/Controllers/AuthorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Firehose.Web.Infrastructure;
using System.Reflection;

namespace Firehose.Web.Controllers
{
    public class AuthorsController : BaseController
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            var viewModel = _members;
            return View(viewModel);
        }

        private readonly IEnumerable<IAmACommunityMember> _members;
        private string[] _interfaceNames =
        {
            nameof(IAmACommunityMember),
            nameof(IWorkAtXamarinOrMicrosoft),
            nameof(IAmAXamarinMVP),
            nameof(IAmAMicrosoftMVP),
            nameof(IAmAPodcast),
            nameof(IAmANewsletter),
            nameof(IAmAFrameworkForXamarin),
            nameof(IAmAYoutuber)
        };

        public AuthorsController(IEnumerable<IAmACommunityMember> members)
        {
            _members = GetAuthors();
            var random = new Random();
            _members = _members.OrderBy(r => random.Next()).ToArray();
        }

        private IEnumerable<IAmACommunityMember> GetAuthors()
        {
            var assembly = Assembly.GetAssembly(typeof(IAmACommunityMember));

            var types = assembly.GetTypes();
            var authorTypes = types.Where(t => typeof(IAmACommunityMember).IsAssignableFrom(t) &&
                !_interfaceNames.Contains(t.Name));

            foreach (var authorType in authorTypes)
            {
                var author = (IAmACommunityMember)Activator.CreateInstance(authorType);
                yield return author;
            }
        }
    }
}

Firehose/Firehose.Web/Controllers/FeedController.cs
using System;
using System.Globalization;
using System.ServiceModel.Syndication;
using Firehose.Web.Infrastructure;

namespace Firehose.Web.Controllers
{
    public class FeedController : BaseController
    {
        private readonly NewCombinedFeedSource _combinedFeedSource;

        public FeedController(NewCombinedFeedSource combinedFeedSource)
        {
            _combinedFeedSource = combinedFeedSource;
        }

        public RssFeedResult Index(int? numPosts = 150, string lang = "mixed")
        {
            var feed = GetFeed(numPosts, lang);
            return new RssFeedResult(feed);
        }

        private SyndicationFeed GetFeed(int? numPosts = 150, string lang = "mixed")
        {
            SyndicationFeed originalFeed = null;

            try
            {
                string language = null;
                if (!string.IsNullOrEmpty(lang) && lang != "mixed")
                    language = CultureInfo.CreateSpecificCulture(lang).Name;

                originalFeed = _combinedFeedSource.LoadFeed(numPosts, language).GetAwaiter().GetResult();
                return originalFeed;
            }
            catch (Exception ex)
            {
                Logger.Error(ex);

                return originalFeed;
            }
        }
    }
}

Firehose/Firehose.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Firehose.Web.Models;
using Firehose.Web.Infrastructure;
using System.Reflection;

namespace Firehose.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IEnumerable<IAmACommunityMember> _members;
        private string[] _interfaceNames =
		{
			nameof(IAmACommunityMember),
			nameof(IWorkAtXamarinOrMicrosoft),
			nameof(IAmAXamarinMVP),
			nameof(IAmAMicrosoftMVP),
			nameof(IAmAPodcast),
			nameof(IAmANewsletter),
			nameof(IAmAFrameworkForXamarin),
			nameof(IAmAYoutuber)
		};

        public HomeController(ILogger<HomeController> logger, IEnumerable<IAmACommunityMember> members)
        {
            _logger = logger;
            _members = GetAuthors();
        }

        private IEnumerable<IAmACommunityMember> GetAuthors()
        {
            var assembly = Assembly.GetAssembly(typeof(IAmACommunityMember));

            var types = assembly.GetTypes();
            var authorTypes = types.Where(t => typeof(IAmACommunityMember).IsAssignableFrom(t) &&
                !_interfaceNames.Contains(t.Name));

            foreach (var authorType in authorTypes)
            {
                var author = (IAmACommunityMember)Activator.CreateInstance(authorType);
                yield return author;
            }
        }

        public IActionResult Index()
        {
            var viewModel = _members;
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            // TODO: Check if you want to use this or the older code below
            // return View(TempData["LastError"]);
        }
    }
}

Firehose/Firehose.Web/Controllers/PreviewController.cs
using System.Globalization;
using System.Linq;
using System.ServiceModel.Syndication;
using Microsoft.AspNetCore.Mvc;
using Firehose.Web.Infrastructure;
using Firehose.Web.ViewModels;

namespace Firehose.Web.Controllers
{
    public class PreviewController : BaseController
    {
        private readonly NewCombinedFeedSource _combinedFeedSource;

        public PreviewController(NewCombinedFeedSource combinedFeedSource)
        {
            _combinedFeedSource = combinedFeedSource;
        }

        public IActionResult Index()
        {
            var feed = GetFeed();
            return View(new PreviewViewModel(feed, _combinedFeedSource.Tamarins.ToArray()));
        }

        private SyndicationFeed GetFeed()
        {
			var lang = CultureInfo.CreateSpecificCulture("en").Name;
			var feed = _combinedFeedSource.LoadFeed(50, lang).GetAwaiter().GetResult();
            return feed;
        }
    }
}

Firehose/Firehose.Web/Views/Home/Index.cshtml
@using Firehose.Web.Controllers
@using Firehose.Web.Infrastructure
@model IEnumerable<IAmACommunityMember>
@{
  ViewData["Title"] = "Home Page";
  Layout = "~/Views/Shared/_ContainerLayout.cshtml";
}

<h1>Welcome!</h1>
<p>Hi, and welcome to Planet Xamarin!</p>
<p>
    We are an aggregator of content from Xamarin Community members. Why subscribe individually when you can subscribe to one convenient RSS feed, to see all the content generated by the community members in you news reader. If RSS isn't your thing, follow our <a href="http://twitter.com/planetxamarin">Twitter</a> or <a href="http://facebook.com/planetxamarin">Facebook</a> accounts which are automatically updated with the latest content from the community.
</p>
<hr />
<div class="leader row text-center">
    <div class="col-md-4">
        <i class="fa fa-rss"></i>
        <h1>Where's the feed?!</h1>
        <p>
            Point your RSS reader at this page and it'll find it; or subscribe to <a asp-controller="Feed" asp-action="Index">the feed manually.</a>
        </p>
    </div>
    <div class="col-md-4">
        <i class="fa fa-book"></i>
        <h1>Can I just read it here?</h1>
        <p>
            You can, but we don't want to redirect traffic from our people's individual sites. Here's a
            <a asp-controller="Preview" asp-action="Index">sneak peek</a> in case you're still trying to decide
            to subscribe.
        </p>
    </div>
    <div class="col-md-4">
        <i class="fa fa-users"></i>
        <h1>Who are you all?</h1>
        <p>
            We are community members! <br />You can <a asp-controller="Authors" asp-action="Index">read more about us here</a>.
        </p>
    </div>
</div>

<hr />

<h2>Authors' opinions</h2>
<p>

    <ol>
        <li>We pride ourselves on diversity of thought - our strength is in our unique collective viewpoints experiences.</li>
        <li>We love sharing this diversity with the community, and we don't censor or curate these blogs - they represent the authors' opinions.</li>
        <li>We provide a <a href="https://github.com/planetxamarin/planetxamarin#just-xamarin-please">way to opt-in what content gets syndicated</a> and encourage authors to use it.</li>
    </ol>
</p>
<hr />
<h1>Already an author?</h1>
<p>Great! Good to have you aboard!</p>
<p>
    You can show off to the world by incorporating this badge into your blog. If you would have it link back to us, that would be totally awesome!
</p>
<img class="featuredbadge" src="~/img/planetxamarin-featured-badge.png" alt="Featured on Planet Xamarin badge" />

<hr />
<h1>Xamarin Podcasts, Shows, Newsletters & Open-source Software</h1>
<p>
    @foreach (var member in Model.Where(m => m is IAmAPodcast || m is IAmANewsletter || m is IAmAFrameworkForXamarin).ToArray())
    {
        await Html.RenderPartialAsync("PodcastCard", member);
    }
</p>

Firehose/Firehose.Web/Views/Home/PodcastCard.cshtml
@using Firehose.Web.Infrastructure
@using Firehose.Web.Extensions

@model IAmACommunityMember

<div class="col-md-4 profileCard" id="@Model.GetType().Name">
    <img class="mugShot" src="@Model.GravatarImage()" alt="@Model.FirstName @Model.LastName" />
    <div class="mugShotBorder">
    </div>
    <div class="profileCardWrapper">

        <p class="name">@Model.FirstName @Model.LastName</p>
        <p class="twitter">
            <a href="https://twitter.com/@Model.TwitterHandle">@@@Model.TwitterHandle</a>
        </p>

        <p class="description">
            @if (!string.IsNullOrWhiteSpace(Model.ShortBioOrTagLine))
            {

                <text>@Model.FirstName @Model.LastName @Model.ShortBioOrTagLine</text>
            }
        </p>

        <p class="website">
            <a href="@(Model.WebSite.ToString())" title="@Model.WebSite.ToString()">@Model.WebSite.ToString()</a>
        </p>
    </div>
</div>